M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date Tue 27 Jun 2023 09:44:47 AM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-27T09:44:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.1260
%
G90
G05
T1
X3.9Y-3.2
X3.9Y-3.25
X3.9Y-3.3
X5.5Y-3.4
X5.55Y-3.4
X5.6Y-3.4
T2
X4.4Y-3.9
X4.8Y-3.9
X5.4Y-3.8
X5.8Y-3.8
T3
X5.1Y-3.8
X5.1Y-3.9
T4
X3.6488Y-2.8
X3.6488Y-2.9
X5.5Y-2.8
X5.5Y-2.9
T5
X4.3Y-3.2
X4.3Y-3.3
X4.3Y-3.4
X4.3Y-3.5
X4.4Y-3.2
X4.4Y-3.3
X4.4Y-3.4
X4.4Y-3.5
T6
X3.2Y-2.7
X3.2Y-4.3
X6.3Y-2.7
X6.3Y-4.3
T0
M30
